language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SJi6eEcpynYGkA4TB3su4+1P5EV4tf42c69wiLmiVom/x5cK6l/ZZq/xuSCr1h1AZaFk4xB+T1N5WiWmQFcal9M8laG/FK190B3+IPqsf+DwQB+Ew6uNz6NfeJUFWGHpRS/qibfMFhxATEYY66b2+7IkTXgGMhULcdT4Bm6PId1DmypAPa2T3ROauYh6Q9xmJnSuBuTNAyF+cSt54EFRr2F0m1JvtYklbP+weRggIdiH5DZFT7C/izF2YoTvYNZ3yZO4Cv6QiIcTwlaxnX8I7s5KruDgZ/8gSQloSa2y9/rCDTrqiSpcgB7W7Jg6Ul39OMuu4guy3BCOJIYVHx06f/dXCroCmv6JrwNPoWyMn92pg5O8DxRz2oXj5aCss153PLQLf4T32jt5lCMyVn0m+LJy72NfebiSRkXf31Kqx6dZgocB4M/Yvdn7XOSVqdWpf8Q/I1Vk6YV4/VomfhbD55wAxyTCEWeTqmxZGVYvFn/BPPzB+t31qPC/GK3P4nuw6lKT2Bc8kl0EcBtR8wsJdej8eZ6k/xL0Wr9YzuXvDlWwkiVAHr3gUpU+Sy4lEd9iAye/bLL+8pbG8XS+14IYU5gWegC0f86ywlgA+J3k3VASbIfR3b6AX7pZwQEd+AALyHDSW1FPSbEx01BjlGHVyvCIFr2JMqFYympaMaqpdKs=
  file:
    - 'rehype-highlight.js'
    - 'rehype-highlight.min.js'
  on:
    tags: true
